#!C:\Program Files\nodejs\node.exe

let request = require("request");
let Phrase = require("js_tutorial_palindrome");
let url = "https://cdn.learnenough.com/phrases.txt";

request(url, function(error, response, body) {
  body.split("\n").filter(line => { 
    return new Phrase(line).palindrome();
  }).map(find => { 
    console.log("palindrome detected:", find); 
  });
});
