#!C:\Program Files\nodejs\node.exe

let request = require("request");
let Phrase = require("js_tutorial_palindrome");
let url = "https://cdn.learnenough.com/phrases.txt";

request(url, function(error, response, body) {
  let ph = new Phrase();
  body.split("\n").filter(line => {
    ph.content = line;
    if (!ph.palindrome()) return;
    console.log("palindrome detected:", ph.content);
  });
});
